<?php
namespace App\Http\Controllers\Api\V1;
use App\Models\Delivery;use App\Models\DeliveryReceipt;use App\Services\AuditService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;
class DeliveryController{
 public function __construct(private readonly AuditService $audit){}
 public function index(Request $r){$q=Delivery::query()->where('tenant_id',app('tenant.id'))->with('purchaseOrder.supplier:id,legal_name')->latest('id');if($r->filled('status'))$q->where('status',$r->string('status'));return $q->paginate(20);}
 public function show(Delivery $delivery){$this->tenant($delivery);return $this->detail($delivery);}
 public function receive(Request $request,Delivery $delivery){$this->tenant($delivery);abort_if($delivery->status==='complete',422,'Cette livraison est deja complete.');$data=$request->validate(['received_at'=>['required','date'],'observations'=>['nullable','string','max:5000'],'bl'=>['required','file','mimes:pdf,jpg,jpeg,png','max:10240'],'pv'=>['required','file','mimes:pdf,jpg,jpeg,png','max:10240'],'items'=>['required','array','min:1'],'items.*.delivery_item_id'=>['required','integer'],'items.*.quantity_received'=>['required','numeric','gt:0'],'items.*.observations'=>['nullable','string','max:2000']]);$disk=config('filesystems.default','local');$base="tenants/{$delivery->tenant_id}/deliveries/{$delivery->id}";$bl=$request->file('bl');$pv=$request->file('pv');
  $receipt=DB::transaction(function()use($request,$delivery,$data,$disk,$base,$bl,$pv){$receipt=$delivery->receipts()->create(['received_by'=>$request->user()->id,'reference'=>'REC-'.now()->format('Ymd-His').'-'.strtoupper(Str::random(4)),'received_at'=>$data['received_at'],'type'=>'partial','observations'=>$data['observations']??null,'bl_original_name'=>$bl->getClientOriginalName(),'bl_path'=>$bl->store($base.'/bl',$disk),'pv_original_name'=>$pv->getClientOriginalName(),'pv_path'=>$pv->store($base.'/pv',$disk),'disk'=>$disk]);foreach($data['items'] as $row){$item=$delivery->items()->whereKey($row['delivery_item_id'])->lockForUpdate()->firstOrFail();$qty=(float)$row['quantity_received'];abort_if($qty>(float)$item->remaining_quantity,422,'La quantite recue depasse le reliquat.');$item->update(['received_quantity'=>(float)$item->received_quantity+$qty,'remaining_quantity'=>(float)$item->remaining_quantity-$qty]);$receipt->items()->create(['delivery_item_id'=>$item->id,'quantity_received'=>$qty,'observations'=>$row['observations']??null]);}$complete=!$delivery->items()->where('remaining_quantity','>',0)->exists();$receipt->update(['type'=>$complete?'total':'partial']);$delivery->update(['status'=>$complete?'complete':'partial']);return $receipt;});$this->audit->record('delivery.received',$delivery,['receipt_id'=>$receipt->id,'type'=>$receipt->type]);return $this->detail($delivery);}
 public function download(Delivery $delivery,DeliveryReceipt $receipt,string $kind){$this->tenant($delivery);abort_unless($receipt->delivery_id===$delivery->id&&in_array($kind,['bl','pv'],true),404);return Storage::disk($receipt->disk)->download($kind==='bl'?$receipt->bl_path:$receipt->pv_path,$kind==='bl'?$receipt->bl_original_name:$receipt->pv_original_name);}
 private function detail(Delivery $d):Delivery{return $d->fresh()->load(['purchaseOrder.supplier:id,legal_name,email,phone','purchaseOrder:id,reference,supplier_id,currency,total_amount,delivery_location,expected_delivery_at,status','items.purchaseOrderItem','receipts.receiver:id,name,email','receipts.items']);}
 private function tenant(Delivery $d):void{abort_unless((int)$d->tenant_id===(int)app('tenant.id'),404);}
}
