<?php
namespace App\Http\Controllers\Api\V1;
use App\Models\Invoice;use App\Services\AuditService;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;
class InvoiceController{
 public function __construct(private readonly AuditService $audit){}
 public function index(Request $r){$q=Invoice::query()->where('tenant_id',app('tenant.id'))->with(['supplier:id,legal_name','purchaseOrder:id,reference'])->latest('id');if($r->filled('status'))$q->where('status',$r->string('status'));return $q->paginate(20);}
 public function show(Invoice $invoice){$this->tenant($invoice);return $this->detail($invoice);}
 public function control(Request $request,Invoice $invoice){$this->tenant($invoice);abort_unless(in_array($invoice->status,['received','controlled'],true),422,'Cette facture ne peut plus etre controlee.');$data=$request->validate(['comment'=>['nullable','string','max:5000']]);$order=$invoice->purchaseOrder()->with('delivery')->firstOrFail();$difference=$invoice->total_amount-$order->total_amount;$tolerance=max(1,(int)round($order->total_amount*.01));$amountOk=abs($difference)<=$tolerance;$deliveryOk=$order->delivery?->status==='complete';$currencyOk=$invoice->currency===$order->currency;$match=$amountOk&&$deliveryOk&&$currencyOk?'matched':'mismatch';$details=['purchase_order_total'=>$order->total_amount,'invoice_total'=>$invoice->total_amount,'difference'=>$difference,'tolerance'=>$tolerance,'amount_ok'=>$amountOk,'delivery_complete'=>$deliveryOk,'currency_ok'=>$currencyOk];$invoice->update(['status'=>$match==='matched'?'compliant':'controlled','match_status'=>$match,'match_details'=>$details,'control_comment'=>$data['comment']??null,'controlled_by'=>$request->user()->id,'controlled_at'=>now()]);$this->audit->record('invoice.controlled',$invoice,$details);return $this->detail($invoice);}
 public function transmit(Invoice $invoice){$this->tenant($invoice);abort_unless($invoice->status==='compliant',422,'Seule une facture conforme peut etre transmise.');$invoice->update(['status'=>'in_payment','payment_transmitted_at'=>now()]);$this->audit->record('invoice.transmitted_to_payment',$invoice);return $this->detail($invoice);}
 public function markPaid(Request $request,Invoice $invoice){$this->tenant($invoice);abort_unless($invoice->status==='in_payment',422,'Cette facture n est pas en paiement.');abort_unless(in_array($request->user()->roleForTenant(app('tenant.id')),['owner','admin','finance'],true),403);$data=$request->validate(['payment_reference'=>['required','string','max:255'],'paid_at'=>['nullable','date']]);$invoice->update(['status'=>'paid','payment_reference'=>$data['payment_reference'],'paid_at'=>$data['paid_at']??now()]);$this->audit->record('invoice.paid',$invoice);return $this->detail($invoice);}
 public function download(Invoice $invoice){$this->tenant($invoice);return Storage::disk($invoice->disk)->download($invoice->storage_path,$invoice->original_name);}
 private function detail(Invoice $i):Invoice{return $i->fresh()->load(['supplier:id,legal_name,email,niu','purchaseOrder.supplier:id,legal_name','purchaseOrder.delivery','controller:id,name,email']);}private function tenant(Invoice $i):void{abort_unless((int)$i->tenant_id===(int)app('tenant.id'),404);}
}
