<?php
namespace App\Http\Controllers\Api\V1;
use App\Models\PurchaseOrder;
use App\Services\AuditService;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use App\Models\Invoice;
class PurchaseOrderPortalController
{
    public function __construct(private readonly AuditService $audit){}
    public function show(string $token){return $this->find($token)->load(['supplier:id,legal_name,email','purchaseRequest:id,reference,title','items']);}
    public function respond(Request $request,string $token){$order=$this->find($token);abort_unless($order->status==='sent',422,'Une reponse a deja ete enregistree.');$data=$request->validate(['decision'=>['required',Rule::in(['accepted','refused'])],'comment'=>['nullable','string','max:5000']]);$order->update(['status'=>$data['decision'],'notes'=>trim(($order->notes? $order->notes."\n\n":'').'Reponse fournisseur: '.($data['comment']??'Aucun commentaire')),'supplier_responded_at'=>now()]);if($data['decision']==='accepted'){$delivery=$order->delivery()->create(['tenant_id'=>$order->tenant_id,'status'=>'pending_confirmation','planned_at'=>$order->expected_delivery_at]);foreach($order->items as $item)$delivery->items()->create(['purchase_order_item_id'=>$item->id,'ordered_quantity'=>$item->quantity,'received_quantity'=>0,'remaining_quantity'=>$item->quantity]);}app()->instance('tenant.id',$order->tenant_id);$this->audit->record('purchase_order.supplier_'.$data['decision'],$order);return $order->fresh();}
    public function confirmDelivery(Request $request,string $token){$order=$this->find($token);abort_unless($order->status==='accepted'&&$order->delivery,422,'Aucune livraison ne peut etre confirmee.');$data=$request->validate(['planned_at'=>['required','date','after_or_equal:today'],'comment'=>['nullable','string','max:3000']]);$order->delivery->update(['status'=>'confirmed','planned_at'=>$data['planned_at'],'confirmed_at'=>now(),'supplier_comment'=>$data['comment']??null]);app()->instance('tenant.id',$order->tenant_id);$this->audit->record('delivery.confirmed',$order->delivery);return $order->delivery;}
    public function uploadInvoice(Request $request,string $token){$order=$this->find($token);abort_unless($order->status==='accepted',422,'La commande doit etre acceptee.');$data=$request->validate(['invoice_number'=>['required','string','max:100'],'currency'=>['required','string','max:8'],'subtotal'=>['required','integer','min:0'],'tax_amount'=>['required','integer','min:0'],'total_amount'=>['required','integer','min:1'],'issued_at'=>['required','date'],'due_at'=>['required','date','after_or_equal:issued_at'],'file'=>['required','file','mimes:pdf,jpg,jpeg,png','max:10240']]);abort_if(Invoice::query()->where('tenant_id',$order->tenant_id)->where('invoice_number',$data['invoice_number'])->exists(),422,'Ce numero de facture existe deja.');$file=$request->file('file');$disk=config('filesystems.default','local');$path=$file->storeAs("tenants/{$order->tenant_id}/invoices",Str::uuid().'.'.$file->getClientOriginalExtension(),$disk);$invoice=Invoice::query()->create([...$data,'tenant_id'=>$order->tenant_id,'purchase_order_id'=>$order->id,'supplier_id'=>$order->supplier_id,'status'=>'received','original_name'=>$file->getClientOriginalName(),'storage_path'=>$path,'disk'=>$disk,'mime_type'=>$file->getMimeType(),'size_bytes'=>$file->getSize()]);app()->instance('tenant.id',$order->tenant_id);$this->audit->record('invoice.received',$invoice);return response()->json($invoice,201);}
    private function find(string $token): PurchaseOrder{return PurchaseOrder::query()->where('supplier_token_hash',hash('sha256',$token))->whereNull('supplier_token_revoked_at')->where(fn($q)=>$q->whereNull('supplier_token_expires_at')->orWhere('supplier_token_expires_at','>=',now()))->firstOrFail();}
}
