"use client";

import { Clock3, MessageSquareText, Plus, Search } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { PageHeading } from "@/components/page-heading";
import { getInformationRequests } from "@/lib/procuflow-api";
import type { InformationRequestRecord } from "@/lib/types";

const labels={draft:"Brouillon",published:"Envoyée",closed:"Clôturée",archived:"Archivée"};
export default function InformationRequestsPage(){const[rows,setRows]=useState<InformationRequestRecord[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{setRows((await getInformationRequests({search,status})).data);setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Chargement impossible.")}finally{setLoading(false)}},[search,status]);useEffect(()=>{const timer=setTimeout(()=>void load(),200);return()=>clearTimeout(timer)},[load]);return <AppShell><div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><PageHeading eyebrow="Sourcing" title="Demandes d'information" description="Interrogez les fournisseurs avant une consultation et centralisez leurs réponses."/><Link className="primary-button" href="/information-requests/new"><Plus size={16}/>Nouvelle demande</Link></div><section className="app-panel flex flex-wrap gap-3 p-3"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={16}/><input className="field-control pl-9" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Référence ou objet"/></label><select className="field-control w-44" value={status} onChange={event=>setStatus(event.target.value)}><option value="">Tous les statuts</option>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></section>{error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<section className="app-panel overflow-hidden">{loading?<div className="h-64 animate-pulse"/>:rows.length?<div className="divide-y divide-[var(--border)]">{rows.map(row=><Link className="grid gap-3 p-4 hover:bg-[var(--surface-soft)] md:grid-cols-[1fr_auto_auto] md:items-center" href={`/information-requests/${row.id}`} key={row.id}><span><small className="font-semibold text-[var(--violet)]">{row.reference}</small><strong className="mt-1 block">{row.subject}</strong><small className="text-[var(--muted)]">{row.category||"Toutes catégories"}</small></span><span className="text-sm"><b>{row.responses_count??0}</b> / {row.suppliers_count??0} réponses</span><span className="text-right"><span className="status-badge bg-violet-50 text-violet-700">{labels[row.status]}</span><small className="mt-2 flex items-center justify-end gap-1 text-[var(--muted)]"><Clock3 size={13}/>{new Intl.DateTimeFormat("fr-FR").format(new Date(row.response_deadline))}</small></span></Link>)}</div>:<div className="grid min-h-64 place-items-center p-8 text-center"><div><MessageSquareText className="mx-auto text-violet-600" size={34}/><h2 className="mb-1 mt-3 text-lg">Aucune demande d&apos;information</h2><p className="text-sm text-[var(--muted)]">Créez votre première demande pour préparer un sourcing.</p></div></div>}</section></div></AppShell>}
