"use client";

import { Printer } from "lucide-react";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { formatMoney } from "@/lib/format";
import { getAcdeNeed } from "@/lib/procuflow-api";
import type { AcdeKind, AcdeNeedRecord } from "@/lib/types";

const sections:Array<[AcdeKind,string,string]>=[["expectation","A","Attentes"],["constraint","C","Contraintes externes"],["data","D","Données"],["requirement","E","Exigences internes"]];const levels={mandatory:"Obligatoire",desired:"Souhaitée",comfort:"De confort"};
export default function AcdeReportPage(){const{id}=useParams<{id:string}>(),[need,setNeed]=useState<AcdeNeedRecord|null>(null);useEffect(()=>{getAcdeNeed(id).then(setNeed)},[id]);if(!need)return <main className="p-10">Chargement du cahier des charges...</main>;return <main className="mx-auto min-h-screen max-w-5xl bg-white p-8 text-gray-900"><div className="print-hidden mb-6 flex justify-end"><button className="primary-button" onClick={()=>window.print()}><Printer size={16}/>Imprimer / Enregistrer en PDF</button></div><header className="border-b-2 border-violet-700 pb-5"><p className="m-0 text-xs font-bold uppercase tracking-widest text-violet-700">ProcuFlow · Cahier des charges fonctionnel</p><h1 className="mb-2 mt-3 text-3xl">{need.title}</h1><p className="m-0 text-gray-600">{need.context}</p></header><section className="my-6 grid grid-cols-4 gap-3 text-sm"><Box label="Service" value={need.service||"—"}/><Box label="Budget" value={need.budget_amount?formatMoney(need.budget_amount,need.currency||"XAF"):"À définir"}/><Box label="Lieu" value={need.delivery_location||"À définir"}/><Box label="Échéance" value={need.needed_at?new Intl.DateTimeFormat("fr-FR").format(new Date(need.needed_at)):"À définir"}/></section>{sections.map(([kind,letter,title])=><section className="mt-7" key={kind}><h2 className="border-b border-gray-300 pb-2 text-lg"><span className="mr-2 inline-grid h-8 w-8 place-items-center rounded-lg bg-violet-700 text-sm text-white">{letter}</span>{title}</h2><table className="mt-3 w-full border-collapse text-sm"><thead><tr className="bg-violet-50 text-left"><th className="border p-2">Description</th><th className="border p-2">Niveau</th><th className="border p-2">Critère / cible</th><th className="border p-2">Tolérance</th><th className="border p-2">Vérification</th></tr></thead><tbody>{need.items.filter(item=>item.kind===kind).map((item,index)=><tr key={item.id??index}><td className="border p-2">{item.content}</td><td className="border p-2">{levels[item.priority_level]??"Obligatoire"}</td><td className="border p-2">{item.criterion||"—"}{item.target_value?<><br/><b>{item.target_value} {item.unit}</b></>:null}</td><td className="border p-2">{item.tolerance||"—"}</td><td className="border p-2">{item.verification_method||"—"}</td></tr>)}</tbody></table></section>)}<footer className="mt-10 border-t pt-4 text-xs text-gray-500">Document généré par ProcuFlow · {new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(new Date())}</footer></main>}
function Box({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><small className="text-gray-500">{label}</small><strong className="mt-1 block">{value}</strong></div>}
