"use client";
import { Boxes, Save } from "lucide-react";
import { useState } from "react";
import { saveStockCheck } from "@/lib/procuflow-api";
import type { PurchaseRequestRecord, StockCheckRecord } from "@/lib/types";
export function StockCheckPanel({purchaseRequest,onSaved}:{purchaseRequest:PurchaseRequestRecord;onSaved:(check:StockCheckRecord)=>void}){
  const [rows,setRows]=useState(()=>(purchaseRequest.items??[]).map((item)=>{const saved=purchaseRequest.stock_check?.items.find((row)=>row.purchase_request_item_id===item.id);return {id:Number(item.id),description:item.description,requested:Number(item.quantity),isStock:saved?saved.result!=="not_applicable":item.unit!=="service",available:Number(saved?.available_quantity??0)}}));
  const [notes,setNotes]=useState(purchaseRequest.stock_check?.notes??"");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  async function save(){setSaving(true);setError("");try{onSaved(await saveStockCheck(purchaseRequest.id,{notes:notes||undefined,items:rows.map((row)=>({purchase_request_item_id:row.id,available_quantity:row.isStock?row.available:0,is_stock_item:row.isStock}))}))}catch(e){setError(e instanceof Error?e.message:"Controle impossible.")}finally{setSaving(false)}}
  return <article className="app-panel overflow-hidden"><div className="flex items-center gap-3 border-b border-[var(--border)] p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--violet-soft)] text-[var(--violet)]"><Boxes size={18}/></span><span><h2 className="m-0 text-base font-semibold">Disponibilite interne</h2><p className="mb-0 mt-1 text-xs text-[var(--muted)]">Controle obligatoire avant une consultation fournisseur.</p></span></div><div className="divide-y divide-[var(--border)]">{rows.map((row,index)=><div className="grid gap-3 p-4 md:grid-cols-[1fr_150px] md:items-end" key={row.id}><div><strong className="block text-sm">{row.description}</strong><small className="text-[var(--muted)]">Quantite demandee : {row.requested}</small><label className="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={row.isStock} onChange={(e)=>setRows((all)=>all.map((item,i)=>i===index?{...item,isStock:e.target.checked,available:0}:item))}/> Article gere en stock</label></div><label><span className="field-label">Quantite disponible</span><input className="field-control" type="number" min="0" max={row.requested} disabled={!row.isStock} value={row.available} onChange={(e)=>setRows((all)=>all.map((item,i)=>i===index?{...item,available:Math.min(row.requested,Number(e.target.value))}:item))}/></label></div>)}</div><div className="grid gap-3 border-t border-[var(--border)] p-4 md:grid-cols-[1fr_auto] md:items-end"><label><span className="field-label">Note du magasin</span><textarea className="field-control min-h-20" value={notes} onChange={(e)=>setNotes(e.target.value)}/></label><button type="button" className="primary-button" disabled={saving} onClick={()=>void save()}><Save size={16}/>{saving?"Enregistrement...":"Valider le controle"}</button></div>{error?<p className="m-0 bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}</article>;
}
