<?php

use App\Http\Controllers\Api\V1\AcdeNeedController;
use App\Http\Controllers\Api\V1\AcdeDocumentController;
use App\Http\Controllers\Api\V1\ApprovalInboxController;
use App\Http\Controllers\Api\V1\ApprovalWorkflowController;
use App\Http\Controllers\Api\V1\AuditLogController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\AutomationController;
use App\Http\Controllers\Api\V1\ContractController;
use App\Http\Controllers\Api\V1\DashboardController;
use App\Http\Controllers\Api\V1\DeliveryController;
use App\Http\Controllers\Api\V1\DohonePaymentController;
use App\Http\Controllers\Api\V1\InvoiceController;
use App\Http\Controllers\Api\V1\InformationRequestController;
use App\Http\Controllers\Api\V1\InformationRequestPortalController;
use App\Http\Controllers\Api\V1\PurchaseRequestController;
use App\Http\Controllers\Api\V1\PurchaseRequestDocumentController;
use App\Http\Controllers\Api\V1\PurchaseOrderController;
use App\Http\Controllers\Api\V1\PurchaseOrderPortalController;
use App\Http\Controllers\Api\V1\OfferComparisonController;
use App\Http\Controllers\Api\V1\PasswordResetController;
use App\Http\Controllers\Api\V1\ProcurementPolicyController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\RfqController;
use App\Http\Controllers\Api\V1\StockCheckController;
use App\Http\Controllers\Api\V1\SubscriptionController;
use App\Http\Controllers\Api\V1\SupplierController;
use App\Http\Controllers\Api\V1\SupplierDocumentController;
use App\Http\Controllers\Api\V1\SupplierEvaluationController;
use App\Http\Controllers\Api\V1\SupplierPortalController;
use App\Http\Controllers\Api\V1\TenantController;
use App\Http\Controllers\Api\V1\TeamController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::middleware('throttle:10,1')->group(function () {
        Route::post('/auth/register', [AuthController::class, 'register']);
        Route::post('/auth/login', [AuthController::class, 'login']);
        Route::post('/auth/forgot-password', [PasswordResetController::class, 'forgot']);
        Route::post('/auth/reset-password', [PasswordResetController::class, 'reset']);
        Route::get('/invitations/{token}', [TeamController::class, 'showInvitation']);
        Route::post('/invitations/{token}/accept', [TeamController::class, 'acceptInvitation']);
    });

    Route::middleware('throttle:60,1')->prefix('supplier-portal/rfqs/{token}')->group(function () {
        Route::get('/', [SupplierPortalController::class, 'show']);
        Route::put('/offer', [SupplierPortalController::class, 'saveOffer']);
        Route::post('/offer/submit', [SupplierPortalController::class, 'submitOffer']);
        Route::post('/decline', [SupplierPortalController::class, 'decline']);
        Route::post('/messages', [SupplierPortalController::class, 'message']);
    });
    Route::middleware('throttle:60,1')->prefix('supplier-portal/purchase-orders/{token}')->group(function () {
        Route::get('/', [PurchaseOrderPortalController::class, 'show']);
        Route::post('/respond', [PurchaseOrderPortalController::class, 'respond']);
        Route::post('/confirm-delivery', [PurchaseOrderPortalController::class, 'confirmDelivery']);
        Route::post('/invoices', [PurchaseOrderPortalController::class, 'uploadInvoice']);
    });
    Route::middleware('throttle:60,1')->prefix('supplier-portal/information-requests/{token}')->group(function () {
        Route::get('/', [InformationRequestPortalController::class, 'show']);
        Route::post('/response', [InformationRequestPortalController::class, 'submit']);
        Route::get('/documents/{document}/download', [InformationRequestPortalController::class, 'download']);
    });

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('/auth/me', [AuthController::class, 'me']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/tenants', [TenantController::class, 'index']);
        Route::post('/tenants/{tenant}/switch', [TenantController::class, 'switch']);
    });

    Route::middleware(['auth:sanctum', 'tenant'])->group(function () {
        Route::get('/dashboard', DashboardController::class);
        Route::get('/information-requests', [InformationRequestController::class, 'index']);
        Route::post('/information-requests', [InformationRequestController::class, 'store'])->middleware('permission:rfqs.manage');
        Route::get('/information-requests/{informationRequest}', [InformationRequestController::class, 'show']);
        Route::post('/information-requests/{informationRequest}/publish', [InformationRequestController::class, 'publish'])->middleware('permission:rfqs.manage');
        Route::post('/information-requests/{informationRequest}/close', [InformationRequestController::class, 'close'])->middleware('permission:rfqs.manage');
        Route::post('/information-requests/{informationRequest}/archive', [InformationRequestController::class, 'archive'])->middleware('permission:rfqs.manage');
        Route::post('/information-requests/{informationRequest}/suppliers/{invitation}/regenerate-link', [InformationRequestController::class, 'regenerateLink'])->middleware('permission:rfqs.manage');
        Route::post('/information-requests/{informationRequest}/documents', [InformationRequestController::class, 'upload'])->middleware('permission:rfqs.manage');
        Route::get('/information-requests/{informationRequest}/documents/{document}/download', [InformationRequestController::class, 'download']);
        Route::get('/information-requests/{informationRequest}/suppliers/{invitation}/response/download', [InformationRequestController::class, 'downloadResponse']);
        Route::get('/contracts/summary', [ContractController::class, 'summary']);
        Route::get('/contracts/options', [ContractController::class, 'options']);
        Route::get('/contracts', [ContractController::class, 'index']);
        Route::post('/contracts', [ContractController::class, 'store'])->middleware('permission:contracts.manage');
        Route::get('/contracts/{contract}', [ContractController::class, 'show']);
        Route::put('/contracts/{contract}', [ContractController::class, 'update'])->middleware('permission:contracts.manage');
        Route::delete('/contracts/{contract}', [ContractController::class, 'destroy'])->middleware('permission:contracts.manage');
        Route::post('/contracts/{contract}/activate', [ContractController::class, 'activate'])->middleware('permission:contracts.manage');
        Route::post('/contracts/{contract}/renew', [ContractController::class, 'renew'])->middleware('permission:contracts.manage');
        Route::post('/contracts/{contract}/terminate', [ContractController::class, 'terminate'])->middleware('permission:contracts.manage');
        Route::post('/contracts/{contract}/documents', [ContractController::class, 'uploadDocument'])->middleware('permission:contracts.manage');
        Route::get('/contracts/{contract}/documents/{document}/download', [ContractController::class, 'downloadDocument']);
        Route::delete('/contracts/{contract}/documents/{document}', [ContractController::class, 'deleteDocument'])->middleware('permission:contracts.manage');
        Route::get('/subscription', [SubscriptionController::class, 'show']);
        Route::get('/subscription/payments', [SubscriptionController::class, 'payments'])->middleware('permission:subscription.manage');
        Route::post('/subscription/checkout', [SubscriptionController::class, 'checkout'])->middleware('permission:subscription.manage');
        Route::post('/subscription/cancel', [SubscriptionController::class, 'cancel'])->middleware('permission:subscription.manage');
        Route::post('/subscription/resume', [SubscriptionController::class, 'resume'])->middleware('permission:subscription.manage');
        Route::get('/reports/overview', [ReportController::class, 'overview']);
        Route::get('/reports/budget-variances', [ReportController::class, 'budget']);
        Route::get('/reports/supplier-performance', [ReportController::class, 'suppliers']);
        Route::get('/reports/snapshots', [ReportController::class, 'snapshots']);
        Route::get('/reports/export', [ReportController::class, 'export']);
        Route::post('/reports/generate', [ReportController::class, 'generate'])->middleware('permission:reports.generate');
        Route::get('/tenant', [TenantController::class, 'current']);
        Route::put('/tenant', [TenantController::class, 'update'])->middleware('permission:tenant.manage');
        Route::get('/team', [TeamController::class, 'index'])->middleware('permission:team.manage');
        Route::post('/team/invitations', [TeamController::class, 'invite'])->middleware('permission:team.manage');
        Route::delete('/team/invitations/{invitation}', [TeamController::class, 'revokeInvitation'])->middleware('permission:team.manage');
        Route::put('/team/members/{user}', [TeamController::class, 'updateMember'])->middleware('permission:team.manage');
        Route::delete('/team/members/{user}', [TeamController::class, 'removeMember'])->middleware('permission:team.manage');
        Route::get('/audit-logs', [AuditLogController::class, 'index']);
        Route::get('/notifications', [AutomationController::class, 'notifications']);
        Route::post('/notifications/read-all', [AutomationController::class, 'readAll']);
        Route::post('/notifications/{notification}/read', [AutomationController::class, 'read']);
        Route::get('/automation-settings', [AutomationController::class, 'settings']);
        Route::put('/automation-settings', [AutomationController::class, 'update'])->middleware('permission:automations.manage');
        Route::post('/automations/run', [AutomationController::class, 'run'])->middleware('permission:automations.manage');
        Route::apiResource('/suppliers', SupplierController::class)->only(['index', 'show']);
        Route::apiResource('/suppliers', SupplierController::class)->only(['store', 'update', 'destroy'])->middleware('permission:suppliers.manage');
        Route::post('/suppliers/{supplier}/submit', [SupplierController::class, 'submit'])->middleware('permission:suppliers.manage');
        Route::post('/suppliers/{supplier}/approve', [SupplierController::class, 'approve'])->middleware('permission:suppliers.manage');
        Route::post('/suppliers/{supplier}/suspend', [SupplierController::class, 'suspend'])->middleware('permission:suppliers.manage');
        Route::post('/suppliers/{supplier}/reactivate', [SupplierController::class, 'reactivate'])->middleware('permission:suppliers.manage');
        Route::get('/suppliers/{supplier}/documents', [SupplierDocumentController::class, 'index']);
        Route::post('/suppliers/{supplier}/documents', [SupplierDocumentController::class, 'store'])->middleware('permission:suppliers.manage');
        Route::get('/suppliers/{supplier}/documents/{document}/download', [SupplierDocumentController::class, 'download']);
        Route::delete('/suppliers/{supplier}/documents/{document}', [SupplierDocumentController::class, 'destroy'])->middleware('permission:suppliers.manage');
        Route::get('/suppliers/{supplier}/evaluations', [SupplierEvaluationController::class, 'index']);
        Route::post('/suppliers/{supplier}/evaluations', [SupplierEvaluationController::class, 'store'])->middleware('permission:suppliers.manage');
        Route::apiResource('/acde-needs', AcdeNeedController::class)->only(['index', 'show']);
        Route::apiResource('/acde-needs', AcdeNeedController::class)->only(['store'])->middleware('permission:requests.create');
        Route::apiResource('/acde-needs', AcdeNeedController::class)->only(['update', 'destroy'])->middleware('permission:requests.manage');
        Route::post('/acde-needs/{acdeNeed}/documents', [AcdeDocumentController::class, 'store'])->middleware('permission:requests.create');
        Route::get('/acde-needs/{acdeNeed}/documents/{document}/download', [AcdeDocumentController::class, 'download']);
        Route::delete('/acde-needs/{acdeNeed}/documents/{document}', [AcdeDocumentController::class, 'destroy'])->middleware('permission:requests.create');
        Route::apiResource('/purchase-requests', PurchaseRequestController::class)->only(['index', 'show']);
        Route::apiResource('/purchase-requests', PurchaseRequestController::class)->only(['store'])->middleware('permission:requests.create');
        Route::apiResource('/purchase-requests', PurchaseRequestController::class)->only(['update', 'destroy'])->middleware('permission:requests.manage');
        Route::post('/purchase-requests/{purchaseRequest}/submit', [PurchaseRequestController::class, 'submit'])->middleware('permission:requests.create');
        Route::post('/purchase-requests/{purchaseRequest}/approve', [PurchaseRequestController::class, 'approve']);
        Route::post('/purchase-requests/{purchaseRequest}/reject', [PurchaseRequestController::class, 'reject']);
        Route::post('/purchase-requests/{purchaseRequest}/documents', [PurchaseRequestDocumentController::class, 'store'])->middleware('permission:requests.create');
        Route::get('/purchase-requests/{purchaseRequest}/documents/{document}/download', [PurchaseRequestDocumentController::class, 'download']);
        Route::delete('/purchase-requests/{purchaseRequest}/documents/{document}', [PurchaseRequestDocumentController::class, 'destroy'])->middleware('permission:requests.create');
        Route::get('/purchase-requests/{purchaseRequest}/stock-check', [StockCheckController::class, 'show']);
        Route::put('/purchase-requests/{purchaseRequest}/stock-check', [StockCheckController::class, 'store'])->middleware('permission:stock.check');
        Route::get('/procurement-policy', [ProcurementPolicyController::class, 'show']);
        Route::put('/procurement-policy', [ProcurementPolicyController::class, 'update'])->middleware('permission:workflows.manage');
        Route::get('/rfqs', [RfqController::class, 'index']);
        Route::post('/rfqs', [RfqController::class, 'store'])->middleware('permission:rfqs.manage');
        Route::get('/rfqs/{rfq}', [RfqController::class, 'show']);
        Route::post('/rfqs/{rfq}/publish', [RfqController::class, 'publish'])->middleware('permission:rfqs.manage');
        Route::post('/rfqs/{rfq}/close', [RfqController::class, 'close'])->middleware('permission:rfqs.manage');
        Route::post('/rfqs/{rfq}/suppliers/{invitation}/regenerate-link', [RfqController::class, 'regenerateLink'])->middleware('permission:rfqs.manage');
        Route::post('/rfqs/{rfq}/suppliers/{invitation}/revoke-link', [RfqController::class, 'revokeLink'])->middleware('permission:rfqs.manage');
        Route::post('/rfqs/{rfq}/exception', [RfqController::class, 'requestException'])->middleware('permission:rfqs.manage');
        Route::post('/rfqs/{rfq}/exception/decision', [RfqController::class, 'decideException']);
        Route::post('/rfqs/{rfq}/messages', [RfqController::class, 'message'])->middleware('permission:rfqs.manage');
        Route::get('/rfqs/{rfq}/comparison', [OfferComparisonController::class, 'show']);
        Route::post('/rfqs/{rfq}/comparison/generate', [OfferComparisonController::class, 'generate'])->middleware('permission:rfqs.manage');
        Route::put('/rfqs/{rfq}/comparison/weights', [OfferComparisonController::class, 'updateWeights'])->middleware('permission:rfqs.manage');
        Route::put('/rfqs/{rfq}/comparison/assessments/{assessment}', [OfferComparisonController::class, 'updateAssessment'])->middleware('permission:rfqs.manage');
        Route::put('/rfqs/{rfq}/comparison/synthesis', [OfferComparisonController::class, 'updateSynthesis'])->middleware('permission:rfqs.manage');
        Route::post('/rfqs/{rfq}/comparison/submit', [OfferComparisonController::class, 'submit'])->middleware('permission:rfqs.manage');
        Route::post('/rfqs/{rfq}/comparison/decision', [OfferComparisonController::class, 'decide']);
        Route::get('/purchase-orders', [PurchaseOrderController::class, 'index']);
        Route::post('/purchase-orders', [PurchaseOrderController::class, 'store'])->middleware('permission:orders.manage');
        Route::get('/purchase-orders/{purchaseOrder}', [PurchaseOrderController::class, 'show']);
        Route::put('/purchase-orders/{purchaseOrder}', [PurchaseOrderController::class, 'update'])->middleware('permission:orders.manage');
        Route::post('/purchase-orders/{purchaseOrder}/submit', [PurchaseOrderController::class, 'submit'])->middleware('permission:orders.manage');
        Route::post('/purchase-orders/{purchaseOrder}/decision', [PurchaseOrderController::class, 'decide']);
        Route::post('/purchase-orders/{purchaseOrder}/send', [PurchaseOrderController::class, 'send'])->middleware('permission:orders.manage');
        Route::post('/purchase-orders/{purchaseOrder}/revoke-link', [PurchaseOrderController::class, 'revokeLink'])->middleware('permission:orders.manage');
        Route::get('/deliveries', [DeliveryController::class, 'index']);
        Route::get('/deliveries/{delivery}', [DeliveryController::class, 'show']);
        Route::post('/deliveries/{delivery}/receipts', [DeliveryController::class, 'receive'])->middleware('permission:deliveries.receive');
        Route::get('/deliveries/{delivery}/receipts/{receipt}/{kind}', [DeliveryController::class, 'download']);
        Route::get('/invoices', [InvoiceController::class, 'index']);
        Route::get('/invoices/{invoice}', [InvoiceController::class, 'show']);
        Route::post('/invoices/{invoice}/control', [InvoiceController::class, 'control'])->middleware('permission:invoices.control');
        Route::post('/invoices/{invoice}/transmit', [InvoiceController::class, 'transmit'])->middleware('permission:invoices.transmit');
        Route::post('/invoices/{invoice}/paid', [InvoiceController::class, 'markPaid'])->middleware('permission:payments.confirm');
        Route::get('/invoices/{invoice}/download', [InvoiceController::class, 'download']);
        Route::get('/approval-workflow', [ApprovalWorkflowController::class, 'show']);
        Route::put('/approval-workflow', [ApprovalWorkflowController::class, 'update'])->middleware('permission:workflows.manage');
        Route::get('/approvals/inbox', ApprovalInboxController::class);
        Route::post('/payments/dohone/start', [DohonePaymentController::class, 'start'])->middleware('permission:invoices.transmit');
    });

    Route::get('/payments/dohone/notify', [DohonePaymentController::class, 'notify']);
    Route::get('/subscriptions/dohone/notify', [SubscriptionController::class, 'notify'])
        ->middleware('throttle:60,1')
        ->name('subscriptions.dohone.notify');
});
