"use client";

import { BellRing, Play, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { PageHeading } from "@/components/page-heading";
import { getAutomationSettings, runAutomations, updateAutomationSettings } from "@/lib/procuflow-api";
import type { AutomationSettings } from "@/lib/types";

const initial: AutomationSettings = { email_enabled: true, in_app_enabled: true, rfq_reminder_days: 2, approval_reminder_hours: 48, delivery_reminder_days: 0, invoice_reminder_days: 3, document_expiry_days: 30, contract_expiry_days: 90 };

export default function AutomationsPage() {
  const [form, setForm] = useState(initial), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { getAutomationSettings().then(setForm).catch(() => undefined); }, []);
  async function save() { setBusy(true); try { setForm(await updateAutomationSettings(form)); setMessage("Reglages enregistres."); } catch (error) { setMessage(error instanceof Error ? error.message : "Enregistrement impossible."); } finally { setBusy(false); } }
  async function run() { setBusy(true); try { const result = await runAutomations(); setMessage(`${result.events} alerte(s) generee(s).`); } catch (error) { setMessage(error instanceof Error ? error.message : "Execution impossible."); } finally { setBusy(false); } }
  return <AppShell><div className="space-y-5"><PageHeading title="Automatisations" description="Configurez les relances et alertes envoyees par ProcuFlow." /><section className="app-panel p-4"><div className="flex items-center gap-2"><BellRing size={18} /><h2 className="m-0 text-base font-semibold">Canaux</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Toggle label="Notifications dans l'application" checked={form.in_app_enabled} onChange={value => setForm({ ...form, in_app_enabled: value })} /><Toggle label="Notifications par e-mail" checked={form.email_enabled} onChange={value => setForm({ ...form, email_enabled: value })} /></div></section><section className="app-panel p-4"><h2 className="m-0 text-base font-semibold">Delais de relance</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Offres RFQ avant echeance" suffix="jours" value={form.rfq_reminder_days} onChange={value => setForm({ ...form, rfq_reminder_days: value })} /><NumberField label="Validation commande apres" suffix="heures" value={form.approval_reminder_hours} onChange={value => setForm({ ...form, approval_reminder_hours: value })} /><NumberField label="Livraison attendue" suffix="jours" value={form.delivery_reminder_days} onChange={value => setForm({ ...form, delivery_reminder_days: value })} /><NumberField label="Facture avant echeance" suffix="jours" value={form.invoice_reminder_days} onChange={value => setForm({ ...form, invoice_reminder_days: value })} /><NumberField label="Document avant expiration" suffix="jours" value={form.document_expiry_days} onChange={value => setForm({ ...form, document_expiry_days: value })} /><NumberField label="Contrat avant echeance" suffix="jours" value={form.contract_expiry_days} onChange={value => setForm({ ...form, contract_expiry_days: value })} /></div><div className="mt-5 flex flex-wrap justify-end gap-2"><button className="secondary-button" disabled={busy} onClick={() => void run()}><Play size={15} />Executer maintenant</button><button className="primary-button" disabled={busy} onClick={() => void save()}><Save size={15} />Enregistrer</button></div>{message ? <p className="mb-0 mt-3 rounded-xl bg-violet-50 p-3 text-sm text-violet-700">{message}</p> : null}</section><section className="app-panel p-4 text-sm"><strong>Planification active</strong><p className="mb-0 mt-1 text-[var(--muted)]">Le moteur s&apos;execute chaque jour a 07:00. Une meme alerte n&apos;est envoyee qu&apos;une fois par jour.</p></section></div></AppShell>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between rounded-xl border border-[var(--border)] p-3"><span className="font-semibold">{label}</span><input className="h-5 w-5 accent-violet-700" type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} /></label>; }
function NumberField({ label, suffix, value, onChange }: { label: string; suffix: string; value: number; onChange: (value: number) => void }) { return <label><span className="field-label">{label}</span><div className="flex items-center gap-2"><input className="field-control" min={0} type="number" value={value} onChange={event => onChange(Number(event.target.value))} /><span className="text-xs text-[var(--muted)]">{suffix}</span></div></label>; }
